export const TOOL_CATEGORIES = [
  {
    id: "optimize",
    label: "Optimize",
    color: "#5a4bff",
    tools: [
      {
        id: "compress",
        label: "Compress Image",
        icon: "⊞",
        desc: "Shrink JPG, PNG or WEBP file size while keeping quality",
        endpoint: "/compress",
        multiFile: false,
        accepts: "image/*",
        fields: [
          { name: "quality", label: "Quality (5–95)", type: "number", placeholder: "75" },
          { name: "format", label: "Output format", type: "select", options: [
            { value: "jpeg", label: "JPG" }, { value: "webp", label: "WEBP" }, { value: "png", label: "PNG (lossless)" },
          ] },
          { name: "background", label: "Background for transparent areas", type: "color", placeholder: "#ffffff" },
        ],
      },
      {
        id: "resize",
        label: "Resize Image",
        icon: "⤢",
        desc: "Set exact pixel dimensions or scale by percent",
        endpoint: "/resize",
        multiFile: false,
        filesParamName: "files",
        customPage: "resize",
        accepts: "image/*",
        fields: [],
      },
      {
        id: "bulk-resize",
        label: "Bulk Image Resizer",
        icon: "⤢",
        desc: "Resize dozens of images at once, all to the same dimensions",
        endpoint: "/resize",
        multiFile: true,
        filesParamName: "files",
        customPage: "resize",
        accepts: "image/*",
        fields: [],
      },
    ],
  },
  {
    id: "edit",
    label: "Edit",
    color: "#ffb648",
    tools: [
      {
        id: "crop",
        label: "Crop Image",
        icon: "⊡",
        desc: "Drag a frame to choose exactly what stays in the shot",
        endpoint: "/crop",
        multiFile: false,
        accepts: "image/*",
        fields: [
          { name: "x1", label: "Crop area", type: "imageCropSelect", placeholder: "" },
        ],
      },
      {
        id: "rotate",
        label: "Rotate Image",
        icon: "↻",
        desc: "Rotate 90° at a time or flip on either axis",
        endpoint: "/rotate",
        multiFile: false,
        accepts: "image/*",
        fields: [
          { name: "angle", label: "Rotation angle", type: "select", options: [
            { value: "0", label: "No rotation" }, { value: "90", label: "90° clockwise" },
            { value: "180", label: "180°" }, { value: "270", label: "270° (90° counter-clockwise)" },
          ] },
          { name: "flip_h", label: "Flip horizontal", type: "checkbox" },
          { name: "flip_v", label: "Flip vertical", type: "checkbox" },
        ],
      },
      {
        id: "watermark",
        label: "Watermark Image",
        icon: "◈",
        desc: "Stamp text over your image with chosen position and opacity",
        endpoint: "/watermark",
        multiFile: false,
        accepts: "image/*",
        fields: [
          { name: "text", label: "Watermark text", type: "text", placeholder: "© your name" },
          { name: "opacity", label: "Opacity (0.1–1.0)", type: "number", placeholder: "0.5" },
          { name: "font_size", label: "Font size", type: "number", placeholder: "36" },
          { name: "position", label: "Position", type: "select", options: [
            { value: "bottom-right", label: "Bottom right" }, { value: "bottom-left", label: "Bottom left" },
            { value: "top-right", label: "Top right" }, { value: "top-left", label: "Top left" },
            { value: "center", label: "Center" },
          ] },
        ],
      },
      {
        id: "photo-editor",
        label: "Photo Editor",
        icon: "✎",
        desc: "Adjust brightness, contrast, saturation and add a caption",
        endpoint: "/photo-editor",
        multiFile: false,
        accepts: "image/*",
        fields: [
          { name: "brightness", label: "Brightness (0.3–2.0)", type: "number", placeholder: "1.0" },
          { name: "contrast", label: "Contrast (0.3–2.0)", type: "number", placeholder: "1.0" },
          { name: "saturation", label: "Saturation (0–2.0)", type: "number", placeholder: "1.0" },
          { name: "blur", label: "Blur (0–10)", type: "number", placeholder: "0" },
          { name: "caption", label: "Caption text", type: "text", placeholder: "" },
          { name: "caption_color", label: "Caption color", type: "color", placeholder: "#ffffff" },
          { name: "caption_size", label: "Caption size", type: "number", placeholder: "36" },
        ],
      },
      {
        id: "meme-generator",
        label: "Meme Generator",
        icon: "😂",
        desc: "Add bold top and bottom captions to any image",
        endpoint: "/meme-generator",
        multiFile: false,
        accepts: "image/*",
        fields: [
          { name: "top_text", label: "Top text", type: "text", placeholder: "" },
          { name: "bottom_text", label: "Bottom text", type: "text", placeholder: "" },
        ],
      },
      {
        id: "blur-face",
        label: "Blur Face",
        icon: "◍",
        desc: "Automatically detect and blur faces to protect privacy",
        endpoint: "/blur-face",
        multiFile: false,
        accepts: "image/*",
        badge: "Pro",
        fields: [
          { name: "strength", label: "Blur strength", type: "number", placeholder: "35" },
        ],
      },
      {
        id: "flip",
        label: "Flip Image",
        icon: "⇋",
        desc: "Mirror an image horizontally or vertically",
        endpoint: "/rotate",
        multiFile: false,
        accepts: "image/*",
        fields: [
          { name: "angle", label: "", type: "number", placeholder: "0", hidden: true },
          { name: "flip_h", label: "Flip horizontal", type: "checkbox" },
          { name: "flip_v", label: "Flip vertical", type: "checkbox" },
        ],
      },
      {
        id: "collage",
        label: "Collage Maker",
        icon: "▦",
        desc: "Arrange several photos into one grid collage",
        endpoint: "/collage",
        multiFile: true,
        accepts: "image/*",
        fields: [
          { name: "columns", label: "Columns", type: "number", placeholder: "3" },
          { name: "spacing", label: "Spacing between photos (px)", type: "number", placeholder: "12" },
          { name: "cell_size", label: "Cell size (px)", type: "number", placeholder: "400" },
          { name: "background", label: "Background color", type: "color", placeholder: "#ffffff" },
        ],
      },
      {
        id: "color-picker",
        label: "Color Picker",
        icon: "◐",
        desc: "Click anywhere on a photo to read its exact color",
        clientOnly: true,
        accepts: "image/*",
        fields: [],
      },
    ],
  },
  {
    id: "convert",
    label: "Convert",
    color: "#457b9d",
    tools: [
      {
        id: "convert-to-jpg",
        label: "Convert to JPG",
        icon: "→",
        desc: "Turn PNG, WEBP, GIF or BMP images into JPG, in bulk",
        endpoint: "/convert-to-jpg",
        multiFile: true,
        accepts: "image/*",
        fields: [
          { name: "background", label: "Background for transparent areas", type: "color", placeholder: "#ffffff" },
          { name: "quality", label: "Quality", type: "number", placeholder: "92" },
        ],
      },
      {
        id: "convert-from-jpg",
        label: "Convert from JPG",
        icon: "←",
        desc: "Turn JPGs into PNG, WEBP or an animated GIF",
        endpoint: "/convert-from-jpg",
        multiFile: true,
        accepts: "image/*",
        fields: [
          { name: "target_format", label: "Target format", type: "select", options: [
            { value: "png", label: "PNG" }, { value: "webp", label: "WEBP" },
            { value: "bmp", label: "BMP" }, { value: "gif", label: "GIF (animated if multiple files)" },
          ] },
          { name: "gif_frame_ms", label: "GIF frame duration (ms)", type: "number", placeholder: "500" },
        ],
      },
      {
        id: "html-to-image",
        label: "HTML to Image",
        icon: "◇",
        desc: "Render a webpage URL or raw HTML into a PNG or JPG",
        endpoint: "/html-to-image",
        noFile: true,
        badge: "Pro",
        fields: [
          { name: "url", label: "Page URL (leave blank to use raw HTML below)", type: "text", placeholder: "https://example.com" },
          { name: "html", label: "Raw HTML", type: "textarea", placeholder: "<h1>Hello</h1>" },
          { name: "width", label: "Viewport width", type: "number", placeholder: "1280" },
          { name: "height", label: "Viewport height", type: "number", placeholder: "800" },
          { name: "out_format", label: "Output format", type: "select", options: [
            { value: "png", label: "PNG" }, { value: "jpg", label: "JPG" },
          ] },
        ],
      },
      {
        id: "image-converter",
        label: "Image Converter",
        icon: "⇄",
        desc: "Convert between JPG, PNG, WEBP, BMP and GIF in bulk",
        endpoint: "/image-converter",
        multiFile: true,
        accepts: "image/*",
        fields: [
          { name: "target_format", label: "Convert to", type: "select", options: [
            { value: "jpg", label: "JPG" }, { value: "png", label: "PNG" },
            { value: "webp", label: "WEBP" }, { value: "bmp", label: "BMP" }, { value: "gif", label: "GIF" },
          ] },
        ],
      },
      {
        id: "heic-to-jpg",
        label: "HEIC to JPG",
        icon: "→",
        desc: "Convert iPhone HEIC/HEIF photos into standard JPG",
        endpoint: "/convert-to-jpg",
        multiFile: true,
        accepts: ".heic,.heif,image/heic,image/heif",
        fields: [
          { name: "background", label: "Background for transparent areas", type: "color", placeholder: "#ffffff" },
          { name: "quality", label: "Quality", type: "number", placeholder: "92" },
        ],
      },
      {
        id: "png-to-jpg",
        label: "PNG to JPG",
        icon: "→",
        desc: "Flatten PNGs to JPG with a background color of your choice",
        endpoint: "/convert-to-jpg",
        multiFile: true,
        accepts: "image/png",
        fields: [
          { name: "background", label: "Background for transparent areas", type: "color", placeholder: "#ffffff" },
          { name: "quality", label: "Quality", type: "number", placeholder: "92" },
        ],
      },
      {
        id: "jpg-to-png",
        label: "JPG to PNG",
        icon: "←",
        desc: "Turn JPGs into PNGs",
        endpoint: "/convert-from-jpg",
        multiFile: true,
        accepts: "image/jpeg",
        fields: [
          { name: "target_format", label: "", type: "text", placeholder: "png", hidden: true },
        ],
      },
      {
        id: "webp-to-jpg",
        label: "WebP to JPG",
        icon: "→",
        desc: "Convert modern WEBP images into universally-readable JPG",
        endpoint: "/convert-to-jpg",
        multiFile: true,
        accepts: "image/webp",
        fields: [
          { name: "background", label: "Background for transparent areas", type: "color", placeholder: "#ffffff" },
          { name: "quality", label: "Quality", type: "number", placeholder: "92" },
        ],
      },
      {
        id: "svg-converter",
        label: "SVG Converter",
        icon: "◇",
        desc: "Render an SVG vector file into a PNG or JPG",
        endpoint: "/svg-to-raster",
        multiFile: false,
        accepts: ".svg,image/svg+xml",
        fields: [
          { name: "out_format", label: "Output format", type: "select", options: [
            { value: "png", label: "PNG" }, { value: "jpg", label: "JPG" },
          ] },
          { name: "width", label: "Width (px, optional)", type: "number", placeholder: "" },
          { name: "height", label: "Height (px, optional)", type: "number", placeholder: "" },
        ],
      },
      {
        id: "png-to-svg",
        label: "PNG to SVG",
        icon: "◇",
        desc: "Wrap a PNG/JPG in a scalable SVG container",
        endpoint: "/png-to-svg",
        multiFile: false,
        accepts: "image/*",
        fields: [],
      },
      {
        id: "image-to-pdf",
        label: "Image to PDF",
        icon: "▤",
        desc: "Combine one or more images into a single PDF file",
        endpoint: "/image-to-pdf",
        multiFile: true,
        accepts: "image/*",
        fields: [],
      },
    ],
  },
  {
    id: "ai",
    label: "AI Tools",
    color: "#2fbf93",
    tools: [
      {
        id: "remove-background",
        label: "Remove Background",
        icon: "◎",
        desc: "Detect and cut out the background automatically",
        endpoint: "/remove-background",
        multiFile: false,
        accepts: "image/*",
        badge: "Pro",
        fields: [],
      },
      {
        id: "upscale",
        label: "Upscale Image",
        icon: "⤢",
        desc: "Enlarge an image while sharpening the result",
        endpoint: "/upscale",
        multiFile: false,
        accepts: "image/*",
        badge: "Pro",
        fields: [
          { name: "factor", label: "Scale factor", type: "select", options: [
            { value: "2", label: "2×" }, { value: "3", label: "3×" }, { value: "4", label: "4×" },
          ] },
        ],
      },
      {
        id: "image-enlarger",
        label: "Image Enlarger",
        icon: "⤢",
        desc: "Blow up a small image for print or display without losing sharpness",
        endpoint: "/upscale",
        multiFile: false,
        accepts: "image/*",
        badge: "Pro",
        fields: [
          { name: "factor", label: "Scale factor", type: "select", options: [
            { value: "2", label: "2×" }, { value: "3", label: "3×" }, { value: "4", label: "4×" },
          ] },
        ],
      },
    ],
  },
];

export const ALL_TOOLS = TOOL_CATEGORIES.flatMap((c) => c.tools.map((t) => ({ ...t, category: c.id, color: c.color })));


